import type {
  SellerFactoryProfile,
  SellerProduct,
  SellerRfq,
  SellerSeek,
  SellerStats,
  SellerConversation,
} from "./types";

export const initialSellerStats: SellerStats = {
  totalProductViews: 14280,
  productViewsChange: 18.4,
  factoryProfileVisits: 3890,
  profileVisitsChange: 12.1,
  videoSeekPlays: 48600,
  videoPlaysChange: 34.2,
  activeRfqsCount: 58,
  pendingRfqsCount: 8,
  responseRatePercent: 98.4,
  avgResponseTimeHours: 1.8,
  followerCount: 1420,
  totalProductsCount: 8,
  totalSeeksCount: 5,
};

export const initialFactoryProfile: SellerFactoryProfile = {
  name: "Apex Precision Machinery & Forgings",
  slug: "apex-forgings",
  logoUrl:
    "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=200&q=80",
  coverUrl:
    "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=1400&q=80",
  country: "India",
  location: "Pune Industrial Estate, Maharashtra",
  yearsEstablished: 1998,
  factorySize: "42,000 sq.m",
  employees: "480+ Specialists",
  annualTurnover: "$15M - $25M USD",
  exportCountries: ["India", "UAE", "Germany", "Vietnam", "USA", "Saudi Arabia"],
  certifications: ["ISO 9001:2015", "CE Certified", "RoHS Compliant", "TUV Rheinland Verified"],
  description:
    "Tier-1 certified OEM & ODM manufacturer specializing in heavy CNC machining, closed-die forging, automated die-casting, and industrial robotic cells. Supplying global and Indian industrial buyers.",
  productionLines: 12,
  verified: true,
  websiteUrl: "https://www.apex-forgings.com",
  tier: "Gold Plus Verified",
};

export const initialSellerProducts: SellerProduct[] = [
  {
    id: "prod-apex-1",
    name: "Heavy-Duty 5-Axis CNC Precision Machining Center (VMC 1200)",
    slug: "cnc-vmc-1200",
    imageUrl:
      "https://images.unsplash.com/photo-1565043589221-1a6fd9ae45c7?auto=format&fit=crop&w=900&q=80",
    category: "CNC Machine",
    categoryId: "cat-cnc-machine",
    priceInr: 2850000,
    unit: "Set",
    moq: "1 Set",
    status: "Active",
    viewsCount: 4120,
    inquiriesCount: 26,
    specs: {
      "Spindle Speed": "12,000 RPM",
      "Table Size": "1300 x 600 mm",
      "Controller": "Siemens 828D / Fanuc 0i-MF",
      "Axis Travel (X/Y/Z)": "1200 / 600 / 600 mm",
      "Tool Magazine": "24 Tools Arm-Type ATC",
      "Positioning Accuracy": "±0.005 mm",
    },
    description:
      "High rigidity linear guideways designed for heavy-duty metal cutting, automotive parts, mold making, and aerospace components.",
    createdAt: "2026-08-10",
  },
  {
    id: "prod-apex-2",
    name: "Closed-Die Hydraulic Hot Forging Press (1600T Capacity)",
    slug: "hot-forging-press-1600t",
    imageUrl:
      "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=900&q=80",
    category: "Die Casting & Forging",
    categoryId: "cat-die-casting-machine",
    priceInr: 4500000,
    unit: "Set",
    moq: "1 Set",
    status: "Active",
    viewsCount: 3840,
    inquiriesCount: 19,
    specs: {
      "Nominal Force": "16,000 kN",
      "Slide Stroke": "450 mm",
      "Die Height": "950 mm",
      "Working Table": "1200 x 1200 mm",
      "Motor Power": "110 kW",
    },
    description:
      "Automated hydraulic forging press with high-speed cycle times, precise force control, and energy-saving servo hydraulic power pack.",
    createdAt: "2026-08-14",
  },
  {
    id: "prod-apex-3",
    name: "Precision Aluminum Die Casting Automated Machine Cell",
    slug: "die-casting-automated-cell",
    imageUrl:
      "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=900&q=80",
    category: "Die Casting & Forging",
    categoryId: "cat-die-casting-machine",
    priceInr: 3200000,
    unit: "Set",
    moq: "1 Set",
    status: "Active",
    viewsCount: 2790,
    inquiriesCount: 14,
    specs: {
      "Clamping Force": "800 Tons",
      "Injection Stroke": "720 mm",
      "Shot Weight (Al)": "9.5 kg",
      "Automation": "Integrated ABB Robotic Ladler & Extractor",
    },
    description:
      "Fully automated cold chamber die casting unit with automatic spraying, molten metal pouring, and part extraction.",
    createdAt: "2026-08-18",
  },
  {
    id: "prod-apex-4",
    name: "Industrial 6kW Fiber Laser Metal Sheet Cutting Machine",
    slug: "fiber-laser-cutting-6kw",
    imageUrl:
      "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?auto=format&fit=crop&w=900&q=80",
    category: "Laser Cutting",
    categoryId: "cat-laser-cutting-machine",
    priceInr: 2150000,
    unit: "Set",
    moq: "1 Set",
    status: "Active",
    viewsCount: 1980,
    inquiriesCount: 11,
    specs: {
      "Laser Power": "6,000 Watts Raycus/IPG",
      "Cutting Bed Area": "3000 x 1500 mm",
      "Max Cutting (Carbon Steel)": "25 mm",
      "Max Cutting (Stainless)": "14 mm",
      "Positioning Speed": "120 m/min",
    },
    description:
      "Aviation aluminum gantry with dual exchange shuttle tables and smart auto-focus cutting head.",
    createdAt: "2026-08-25",
  },
  {
    id: "prod-apex-5",
    name: "Forged Alloy Steel Crankshaft Blanks & Shaft Components",
    slug: "forged-crankshaft-blanks",
    imageUrl:
      "https://images.unsplash.com/photo-1530124566582-a618bc2615dc?auto=format&fit=crop&w=900&q=80",
    category: "Forging Parts",
    categoryId: "cat-forging-parts",
    priceInr: 12500,
    unit: "Piece",
    moq: "100 Pieces",
    status: "Active",
    viewsCount: 1450,
    inquiriesCount: 9,
    specs: {
      "Material Grade": "42CrMo4 / 40Cr / SAE 4140",
      "Heat Treatment": "Quenched & Tempered (QT)",
      "Surface Finish": "Machined / Shot Blasted",
      "NDT Testing": "100% Ultrasonic + Magnetic Particle",
    },
    description:
      "Custom forged engine crankshafts and heavy-duty drivetrain components manufactured to client drawings.",
    createdAt: "2026-09-01",
  },
];

export const initialSellerSeeks: SellerSeek[] = [
  {
    id: "seek-apex-1",
    title: "5-Axis High-Speed CNC Machining of Titanium Aerospace Turbine Flange",
    videoUrl: "/videos/reel1.mp4",
    thumbnailUrl:
      "https://images.unsplash.com/photo-1565043589221-1a6fd9ae45c7?auto=format&fit=crop&w=600&q=80",
    durationSeconds: 32,
    viewsCount: 18450,
    likesCount: 840,
    commentsCount: 68,
    inquiriesGenerated: 14,
    taggedProductName: "Heavy-Duty 5-Axis CNC Precision Machining Center (VMC 1200)",
    category: "CNC Machining",
    createdAt: "2026-08-20",
    status: "Published",
  },
  {
    id: "seek-apex-2",
    title: "Live 1600-Ton Hydraulic Forging Press in Operation — Red Hot Billet",
    videoUrl: "/videos/reel2.mp4",
    thumbnailUrl:
      "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=600&q=80",
    durationSeconds: 28,
    viewsCount: 14200,
    likesCount: 695,
    commentsCount: 42,
    inquiriesGenerated: 11,
    taggedProductName: "Closed-Die Hydraulic Hot Forging Press (1600T Capacity)",
    category: "Hot Forging",
    createdAt: "2026-08-24",
    status: "Published",
  },
  {
    id: "seek-apex-3",
    title: "Automated Robotic Die Casting Line with Thermal Camera Inspection",
    videoUrl: "/videos/reel1.mp4",
    thumbnailUrl:
      "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=600&q=80",
    durationSeconds: 35,
    viewsCount: 9800,
    likesCount: 430,
    commentsCount: 29,
    inquiriesGenerated: 7,
    taggedProductName: "Precision Aluminum Die Casting Automated Machine Cell",
    category: "Die Casting",
    createdAt: "2026-09-02",
    status: "Published",
  },
  {
    id: "seek-apex-4",
    title: "Factory Quality Lab: CMM Coordinate Measuring Machine 0.001mm Check",
    videoUrl: "/videos/reel2.mp4",
    thumbnailUrl:
      "https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&w=600&q=80",
    durationSeconds: 24,
    viewsCount: 6150,
    likesCount: 310,
    commentsCount: 18,
    inquiriesGenerated: 5,
    category: "Quality Assurance",
    createdAt: "2026-09-08",
    status: "Published",
  },
];

export const initialSellerRfqs: SellerRfq[] = [
  {
    id: "rfq-inq-101",
    buyerName: "Rajesh Kulkarni",
    buyerCompany: "Mahindra Sourcing & Auto Ltd.",
    buyerCountry: "India",
    buyerAvatarUrl:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80",
    productName: "Heavy-Duty 5-Axis CNC Precision Machining Center (VMC 1200)",
    productCategory: "CNC Machine",
    quantityRequested: "3 Sets",
    targetBudgetInr: 8000000,
    deliveryPort: "Nhava Sheva (JNPT), Mumbai, India",
    status: "New",
    createdAt: "2026-09-15 14:30",
    requirements:
      "Looking for 3 units of 5-axis CNC machining centers for automotive gear housing production. Need Siemens controller option, on-site commissioning support in Pune, and 2-year warranty package. Please send FOB & CIF pricing.",
  },
  {
    id: "rfq-inq-102",
    buyerName: "Amitabh Sen",
    buyerCompany: "Kolkata Heavy Engineering Corp",
    buyerCountry: "India",
    buyerAvatarUrl:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80",
    productName: "Closed-Die Hydraulic Hot Forging Press (1600T Capacity)",
    productCategory: "Die Casting & Forging",
    quantityRequested: "1 Set",
    targetBudgetInr: 4200000,
    deliveryPort: "Kolkata Port, India",
    status: "Responded",
    createdAt: "2026-09-14 09:15",
    requirements:
      "Require complete turn-key forging line including induction billet heater and trimming press. Please provide power consumption stats and foundation requirements drawing.",
    quotedPriceInr: 4400000,
    leadTimeDays: 45,
  },
  {
    id: "rfq-inq-103",
    buyerName: "Tariq Al-Mansoor",
    buyerCompany: "Gulf Industrial Fabricators W.L.L.",
    buyerCountry: "United Arab Emirates",
    buyerAvatarUrl:
      "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=150&q=80",
    productName: "Industrial 6kW Fiber Laser Metal Sheet Cutting Machine",
    productCategory: "Laser Cutting",
    quantityRequested: "2 Sets",
    targetBudgetInr: 4000000,
    deliveryPort: "Jebel Ali Port, Dubai",
    status: "Quoted",
    createdAt: "2026-09-12 18:40",
    requirements:
      "Need 6kW high-power fiber laser machines for stainless steel pipe and sheet cutting up to 16mm. Quote CIF Dubai with installation training.",
    quotedPriceInr: 4100000,
    leadTimeDays: 30,
  },
  {
    id: "rfq-inq-104",
    buyerName: "Sunil Varma",
    buyerCompany: "Varma Tractors & Agrotech",
    buyerCountry: "India",
    buyerAvatarUrl:
      "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=150&q=80",
    productName: "Forged Alloy Steel Crankshaft Blanks & Shaft Components",
    productCategory: "Forging Parts",
    quantityRequested: "1,200 Pieces / Month",
    targetBudgetInr: 14000000,
    deliveryPort: "Chennai Port / Road Transport to Hosur",
    status: "New",
    createdAt: "2026-09-16 11:20",
    requirements:
      "Annual supply agreement for tractor engine crankshaft forging blanks (SAE 4140). Please share ultrasonic test certificates and sample lead time.",
  },
];

export const initialSellerConversations: SellerConversation[] = [
  {
    id: "conv-b1",
    buyerId: "b-rajesh",
    buyerName: "Rajesh Kulkarni",
    buyerCompany: "Mahindra Sourcing & Auto",
    buyerCountry: "India",
    buyerAvatarUrl:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80",
    lastMessage: "Can you send the Siemens 828D electrical wiring specification sheet?",
    lastMessageTime: "10 mins ago",
    unreadCount: 1,
    relatedProduct: "Heavy-Duty 5-Axis CNC Precision Machining Center (VMC 1200)",
    status: "active",
    messages: [
      {
        id: "msg-1",
        sender: "buyer",
        text: "Hello Apex team, we reviewed your video Seek demonstrating the 5-axis CNC machining center.",
        timestamp: "Yesterday 16:20",
      },
      {
        id: "msg-2",
        sender: "seller",
        text: "Thank you Rajesh ji. That VMC 1200 machine is equipped with high-rigidity linear roller guideways and 24-tool ATC. Are you looking for delivery in Pune?",
        timestamp: "Yesterday 16:45",
      },
      {
        id: "msg-3",
        sender: "buyer",
        text: "Yes, exactly for our Chakan automotive plant. We need 3 units by end of Q4.",
        timestamp: "Yesterday 17:10",
      },
      {
        id: "msg-4",
        sender: "seller",
        text: "We can guarantee delivery within 35 days with on-site commissioning engineers. I'm attaching our factory inspection report.",
        timestamp: "Today 09:30",
        attachmentType: "product",
        attachmentData: {
          title: "VMC 1200 Technical Brochure & Test Report",
          detail: "Includes spindle runout accuracy and 5-axis repeatability data.",
        },
      },
      {
        id: "msg-5",
        sender: "buyer",
        text: "Can you send the Siemens 828D electrical wiring specification sheet?",
        timestamp: "10 mins ago",
      },
    ],
  },
  {
    id: "conv-b2",
    buyerId: "b-tariq",
    buyerName: "Tariq Al-Mansoor",
    buyerCompany: "Gulf Industrial Fabricators",
    buyerCountry: "UAE",
    buyerAvatarUrl:
      "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=150&q=80",
    lastMessage: "Quotation received, our procurement board is reviewing today.",
    lastMessageTime: "2 hours ago",
    unreadCount: 0,
    relatedProduct: "Industrial 6kW Fiber Laser Metal Sheet Cutting Machine",
    status: "active",
    messages: [
      {
        id: "msg-b2-1",
        sender: "buyer",
        text: "Good day, what is the best CIF Jebel Ali price for 2 sets of 6kW Fiber Laser cutters?",
        timestamp: "Sep 13 11:00",
      },
      {
        id: "msg-b2-2",
        sender: "seller",
        text: "Hello Tariq, we have sent our formal quotation of INR 41,00,000 / Set CIF Dubai with spare nozzles and auto-focus lenses included.",
        timestamp: "Sep 13 14:20",
        attachmentType: "quote",
        attachmentData: {
          title: "Formal Quotation #SF-APEX-2026-89",
          detail: "2x 6kW Fiber Laser Cutters - CIF Dubai Port",
          price: 8200000,
        },
      },
      {
        id: "msg-b2-3",
        sender: "buyer",
        text: "Quotation received, our procurement board is reviewing today.",
        timestamp: "2 hours ago",
      },
    ],
  },
  {
    id: "conv-b3",
    buyerId: "b-sunil",
    buyerName: "Sunil Varma",
    buyerCompany: "Varma Tractors & Agrotech",
    buyerCountry: "India",
    buyerAvatarUrl:
      "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=150&q=80",
    lastMessage: "We have issued RFQ for 1,200 pcs monthly supply of crankshaft forgings.",
    lastMessageTime: "Yesterday",
    unreadCount: 0,
    relatedProduct: "Forged Alloy Steel Crankshaft Blanks & Shaft Components",
    status: "lead",
    messages: [
      {
        id: "msg-b3-1",
        sender: "buyer",
        text: "We have issued RFQ for 1,200 pcs monthly supply of crankshaft forgings.",
        timestamp: "Yesterday 11:20",
      },
    ],
  },
];
